language: julia
os:
    - linux
    - osx
julia:
    - 0.6
notifications:
    email: false
before_script:
    - julia -e 'Pkg.clone("https://github.com/andreasnoack/LinearAlgebra.jl.git")'
after_success:
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("ConvexHull")); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
