language: julia
os:
    - linux
    - osx
julia:
    - 0.6
    - nightly
notifications:
    email: false
sudo: false
before_script:
    - julia -e 'Pkg.clone("https://github.com/andreasnoack/LinearAlgebra.jl.git")'
    - julia -e 'Pkg.clone("https://github.com/JuliaPolyhedra/Polyhedra.jl.git")'
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.test("ConvexHull")'
after_success:
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("ConvexHull")); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
